### ISSUE TITLE
Husky Not Found

### ISSUE THREAD

**Issue by DylanBPY** [truckermudgeon/maps#16]
Hello, I'm one of the devs for [ETS2LA](https://github.com/ETS2LA), we came across this absolutely amazing project, and I'm trying to start testing this out!
NOTE: If you haven't already, please go read @Tumppi066's issue before this!

I forked this repository to the [ETS2LA organization ](https://github.com/ETS2LA/maps), but I can't seem to get the demo running locally. 

I ran `npm install`, which resulted in a `'husky' is not recognized as an internal or external command, operable program or batch file.`, So I installed Husky with `npm install husky --save-dev`, There are no errors during the install and it works as expected. However, I still get this error:
```
C:\Users\Dylan\Documents\Coding\Python\ETS2-Lane-Assist\maps\packages\apps\demo>npm install

> maps@0.0.0 prepare
> husky install

'husky' is not recognized as an internal or external command,
operable program or batch file.
npm error code 1
npm error path C:\Users\Dylan\Documents\Coding\Python\ETS2-Lane-Assist\maps
npm error command failed
npm error command C:\Windows\system32\cmd.exe /d /s /c husky install

npm error A complete log of this run can be found in: C:\Users\Dylan\AppData\Local\npm-cache\_logs\2024-10-04T00_55_27_193Z-debug-0.log
```

This is really cool and will help ETS2LA get closer and closer to completion, I hope you can join us in doing that!

Thanks
- Dylan and the ETS2LA Team

**Comment by truckermudgeon** [comment]
Ahhh.... I noticed you were inside the `packages/apps/demo` subdir when running `npm install`.

This project uses npm workspaces, and things get weird when you try to do things outside of the project root.

If you go back up a few levels to the `maps` root, then run `npm install`, you should have better luck.

**Comment by Tumppi066** [comment]
You probably won't get this working on windows anyways, at least I didn't. Something calls `ln` in an NPM package and that breaks windows compatibility. I ended up running inside of WSL and that worked fine 👍

**Comment by DylanBPY** [comment]
> Ahhh.... I noticed you were inside the `packages/apps/demo` subdir when running `npm install`.
> 
> This project uses npm workspaces, and things get weird when you try to do things outside of the project root.
> 
> If you go back up a few levels to the `maps` root, then run `npm install`, you should have better luck.

I'll try this out but I'm not sure it will work due to the system requirements, I only have an i5 with 16G memory.

**Comment by DylanBPY** [comment]
Doesn't seem to work with my memory amount, looks like Tumppi066 has this covered anyways
