### ISSUE TITLE
Missing output directory causes delayed parser failure

### ISSUE THREAD

**Issue by nautofon** [truckermudgeon/maps#2]
When the output directory specified with `npx parser -o` doesn't exist, the software throws an exception, but does so only *after* doing all the processing, which can take several minutes, wasting users' time. Options to improve this situation include:

- Automatically create the output directory if missing.

- Check for existence of the output directory *before* starting to parse the input files.

- Include something like `mkdir -p dirToWriteFilesTo` in the readme file.

The generator tools might have the same issue (haven't really checked). If so, another option, and in fact the solution I'd suggest for the generator tools, would be to have `-o` default to the value of `-i`.

**Comment by truckermudgeon** [comment]
Ah, good point. I've taken for granted my local directory structure 🙃 

I went with the option to:

> Automatically create the output directory if missing.
